# linux distribution to be used in VM
dist: xenial

services:
  - docker

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - docker -v
  - cp .env.example .env
  # we are using db from docker
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

jobs:
  include:
    # - stage: check_lint
    #   language: python
    #   python: "3.7"
      
    #   name: "Pass Linter"
    #   script: |
    #             # docker-compose run api_test pylint api
    #             python -m pylint api
      
    - stage: py_test
      language: python
      python: "3.7"            
    
      name: "Run Unit test"
      script: |
                docker-compose run api_test python -m pytest -v
                # python -m pytest -v

after_success:
  - echo "Successfully executed jobs"