language: python
python:
  - '3.7'
install:
  - 'pip install pipenv'
  - 'pipenv sync'
script: |
          - 'python -m pytest'
          - 'python -m pylint api'
after_success:
  - echo "RUN code coverate here 'python-codacy-coverage -r coverage.xml' "